<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PermissionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('permissions')->delete();
        
        \DB::table('permissions')->insert(array (
            0 => 
            array (
                'id' => '0195b284-bacd-70f1-ad88-0c3f1efe69b6',
                'name' => 'NotificationsModule.create',
                'guard_name' => 'web',
                'created_at' => '2025-03-20 07:46:37',
                'updated_at' => '2025-03-20 07:46:37',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            1 => 
            array (
                'id' => '0195b284-baf4-7378-9cf2-a23598641158',
                'name' => 'NotificationsModule.read',
                'guard_name' => 'web',
                'created_at' => '2025-03-20 07:46:37',
                'updated_at' => '2025-03-20 07:46:37',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            2 => 
            array (
                'id' => '0195b284-bb24-71bc-aac8-fea851defb9f',
                'name' => 'NotificationsModule.update',
                'guard_name' => 'web',
                'created_at' => '2025-03-20 07:46:37',
                'updated_at' => '2025-03-20 07:46:37',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            3 => 
            array (
                'id' => '0195b284-bb4b-71f6-a816-778e8454cbda',
                'name' => 'NotificationsModule.destroy',
                'guard_name' => 'web',
                'created_at' => '2025-03-20 07:46:38',
                'updated_at' => '2025-03-20 07:46:38',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            4 => 
            array (
                'id' => '0195b286-1fab-7103-b0bd-4abe1e835ad5',
                'name' => 'SmtpAuthsModule.create',
                'guard_name' => 'web',
                'created_at' => '2025-03-20 07:48:09',
                'updated_at' => '2025-03-20 07:48:09',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            5 => 
            array (
                'id' => '0195b286-1fd3-7325-9845-c64159aa6aa7',
                'name' => 'SmtpAuthsModule.read',
                'guard_name' => 'web',
                'created_at' => '2025-03-20 07:48:09',
                'updated_at' => '2025-03-20 07:48:09',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            6 => 
            array (
                'id' => '0195b286-2002-7353-b9e7-cc18c9bb23dc',
                'name' => 'SmtpAuthsModule.update',
                'guard_name' => 'web',
                'created_at' => '2025-03-20 07:48:09',
                'updated_at' => '2025-03-20 07:48:09',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            7 => 
            array (
                'id' => '0195b286-2028-709d-83bc-45ad678c97fe',
                'name' => 'SmtpAuthsModule.destroy',
                'guard_name' => 'web',
                'created_at' => '2025-03-20 07:48:09',
                'updated_at' => '2025-03-20 07:48:09',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            8 => 
            array (
                'id' => '01990e66-68a9-7216-b0f5-b3e2d8f268cc',
                'name' => 'ShopsModule.create',
                'guard_name' => 'web',
                'created_at' => '2025-09-03 07:06:56',
                'updated_at' => '2025-09-03 07:06:56',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            9 => 
            array (
                'id' => '01990e66-68c0-71f4-9b83-22473e5aaf63',
                'name' => 'ShopsModule.read',
                'guard_name' => 'web',
                'created_at' => '2025-09-03 07:06:56',
                'updated_at' => '2025-09-03 07:06:56',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            10 => 
            array (
                'id' => '01990e66-68d4-715a-b9e2-257d0b8bd95a',
                'name' => 'ShopsModule.update',
                'guard_name' => 'web',
                'created_at' => '2025-09-03 07:06:56',
                'updated_at' => '2025-09-03 07:06:56',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            11 => 
            array (
                'id' => '01990e66-68eb-7003-9850-69b27134ab1c',
                'name' => 'ShopsModule.destroy',
                'guard_name' => 'web',
                'created_at' => '2025-09-03 07:06:56',
                'updated_at' => '2025-09-03 07:06:56',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            12 => 
            array (
                'id' => '01990e66-beaa-725a-a0e0-3400adb7da40',
                'name' => 'PublicationsModule.create',
                'guard_name' => 'web',
                'created_at' => '2025-09-03 07:07:18',
                'updated_at' => '2025-09-03 07:07:18',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            13 => 
            array (
                'id' => '01990e66-bebf-72ec-9b5d-2926237a6150',
                'name' => 'PublicationsModule.read',
                'guard_name' => 'web',
                'created_at' => '2025-09-03 07:07:18',
                'updated_at' => '2025-09-03 07:07:18',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            14 => 
            array (
                'id' => '01990e66-bed4-731d-8617-824f96140ba4',
                'name' => 'PublicationsModule.update',
                'guard_name' => 'web',
                'created_at' => '2025-09-03 07:07:18',
                'updated_at' => '2025-09-03 07:07:18',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            15 => 
            array (
                'id' => '01990e66-beed-70f4-bbab-13767368a097',
                'name' => 'PublicationsModule.destroy',
                'guard_name' => 'web',
                'created_at' => '2025-09-03 07:07:18',
                'updated_at' => '2025-09-03 07:07:18',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            16 => 
            array (
                'id' => '01990e66-f53c-7063-9a26-63e1fdf49346',
                'name' => 'CdfServicesModule.create',
                'guard_name' => 'web',
                'created_at' => '2025-09-03 07:07:32',
                'updated_at' => '2025-09-03 07:07:32',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            17 => 
            array (
                'id' => '01990e66-f554-70a2-b9c4-eee335199215',
                'name' => 'CdfServicesModule.read',
                'guard_name' => 'web',
                'created_at' => '2025-09-03 07:07:32',
                'updated_at' => '2025-09-03 07:07:32',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            18 => 
            array (
                'id' => '01990e66-f569-73d5-8549-50d4e928997b',
                'name' => 'CdfServicesModule.update',
                'guard_name' => 'web',
                'created_at' => '2025-09-03 07:07:32',
                'updated_at' => '2025-09-03 07:07:32',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            19 => 
            array (
                'id' => '01990e66-f580-727c-9219-cacc00ef511e',
                'name' => 'CdfServicesModule.destroy',
                'guard_name' => 'web',
                'created_at' => '2025-09-03 07:07:32',
                'updated_at' => '2025-09-03 07:07:32',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            20 => 
            array (
                'id' => '01990e67-1801-70b5-ac6e-3c17c947a963',
                'name' => 'AvatarsModule.create',
                'guard_name' => 'web',
                'created_at' => '2025-09-03 07:07:41',
                'updated_at' => '2025-09-03 07:07:41',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            21 => 
            array (
                'id' => '01990e67-1819-7052-96fb-fb915c7ae93a',
                'name' => 'AvatarsModule.read',
                'guard_name' => 'web',
                'created_at' => '2025-09-03 07:07:41',
                'updated_at' => '2025-09-03 07:07:41',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            22 => 
            array (
                'id' => '01990e67-1831-7042-afcc-71c11ac4788f',
                'name' => 'AvatarsModule.update',
                'guard_name' => 'web',
                'created_at' => '2025-09-03 07:07:41',
                'updated_at' => '2025-09-03 07:07:41',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            23 => 
            array (
                'id' => '01990e67-184b-72c4-91a4-bcc12eb15e1e',
                'name' => 'AvatarsModule.destroy',
                'guard_name' => 'web',
                'created_at' => '2025-09-03 07:07:41',
                'updated_at' => '2025-09-03 07:07:41',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            24 => 
            array (
                'id' => '01990e67-40af-71c3-89b7-d1c1ffefa98b',
                'name' => 'AppUsersModule.create',
                'guard_name' => 'web',
                'created_at' => '2025-09-03 07:07:51',
                'updated_at' => '2025-09-03 07:07:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            25 => 
            array (
                'id' => '01990e67-40c5-71e7-9b53-1e332b3d0905',
                'name' => 'AppUsersModule.read',
                'guard_name' => 'web',
                'created_at' => '2025-09-03 07:07:51',
                'updated_at' => '2025-09-03 07:07:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            26 => 
            array (
                'id' => '01990e67-40dd-707e-92f4-3011d25ee3ac',
                'name' => 'AppUsersModule.update',
                'guard_name' => 'web',
                'created_at' => '2025-09-03 07:07:51',
                'updated_at' => '2025-09-03 07:07:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            27 => 
            array (
                'id' => '01990e67-40f5-7363-bd30-28d58f99f8ae',
                'name' => 'AppUsersModule.destroy',
                'guard_name' => 'web',
                'created_at' => '2025-09-03 07:07:51',
                'updated_at' => '2025-09-03 07:07:51',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            28 => 
            array (
                'id' => '01990e67-e63f-7070-b2a3-d66cb880667f',
                'name' => 'PushNotificationsModule.create',
                'guard_name' => 'web',
                'created_at' => '2025-09-03 07:08:34',
                'updated_at' => '2025-09-03 07:08:34',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            29 => 
            array (
                'id' => '01990e67-e658-70a3-860c-926a7dfe22fe',
                'name' => 'PushNotificationsModule.read',
                'guard_name' => 'web',
                'created_at' => '2025-09-03 07:08:34',
                'updated_at' => '2025-09-03 07:08:34',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            30 => 
            array (
                'id' => '01990e67-e673-7272-a923-84b1218b4b4c',
                'name' => 'PushNotificationsModule.update',
                'guard_name' => 'web',
                'created_at' => '2025-09-03 07:08:34',
                'updated_at' => '2025-09-03 07:08:34',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            31 => 
            array (
                'id' => '01990e67-e68f-70b8-9190-50dd516f6d46',
                'name' => 'PushNotificationsModule.destroy',
                'guard_name' => 'web',
                'created_at' => '2025-09-03 07:08:34',
                'updated_at' => '2025-09-03 07:08:34',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            32 => 
            array (
                'id' => '01990e68-5b73-72e0-a6fc-5a6984abfcb9',
                'name' => 'AppLocalizationsModule.create',
                'guard_name' => 'web',
                'created_at' => '2025-09-03 07:09:04',
                'updated_at' => '2025-09-03 07:09:04',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            33 => 
            array (
                'id' => '01990e68-5b8c-72a9-81f7-dcb4693364a5',
                'name' => 'AppLocalizationsModule.read',
                'guard_name' => 'web',
                'created_at' => '2025-09-03 07:09:04',
                'updated_at' => '2025-09-03 07:09:04',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            34 => 
            array (
                'id' => '01990e68-5ba8-7320-8673-d36d8cb51472',
                'name' => 'AppLocalizationsModule.update',
                'guard_name' => 'web',
                'created_at' => '2025-09-03 07:09:04',
                'updated_at' => '2025-09-03 07:09:04',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            35 => 
            array (
                'id' => '01990e68-5bc3-722d-b73c-27b0f104882c',
                'name' => 'AppLocalizationsModule.destroy',
                'guard_name' => 'web',
                'created_at' => '2025-09-03 07:09:04',
                'updated_at' => '2025-09-03 07:09:04',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            36 => 
            array (
                'id' => '01990e69-c380-73c0-8720-0639f52ae6bc',
                'name' => 'ToponymsModule.create',
                'guard_name' => 'web',
                'created_at' => '2025-09-03 07:10:36',
                'updated_at' => '2025-09-03 07:10:36',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            37 => 
            array (
                'id' => '01990e69-c39b-717d-82d0-4ca1166538b4',
                'name' => 'ToponymsModule.read',
                'guard_name' => 'web',
                'created_at' => '2025-09-03 07:10:36',
                'updated_at' => '2025-09-03 07:10:36',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            38 => 
            array (
                'id' => '01990e69-c3b8-71d7-ad83-8f273a4858a9',
                'name' => 'ToponymsModule.update',
                'guard_name' => 'web',
                'created_at' => '2025-09-03 07:10:36',
                'updated_at' => '2025-09-03 07:10:36',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            39 => 
            array (
                'id' => '01990e69-c3d7-7331-b7d1-591f063bc5ae',
                'name' => 'ToponymsModule.destroy',
                'guard_name' => 'web',
                'created_at' => '2025-09-03 07:10:36',
                'updated_at' => '2025-09-03 07:10:36',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            40 => 
            array (
                'id' => '01990e69-e876-7166-a19d-9de9f0aac14d',
                'name' => 'UsStatesModule.create',
                'guard_name' => 'web',
                'created_at' => '2025-09-03 07:10:45',
                'updated_at' => '2025-09-03 07:10:45',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            41 => 
            array (
                'id' => '01990e69-e890-720a-a55c-ee52d39a14ba',
                'name' => 'UsStatesModule.read',
                'guard_name' => 'web',
                'created_at' => '2025-09-03 07:10:45',
                'updated_at' => '2025-09-03 07:10:45',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            42 => 
            array (
                'id' => '01990e69-e8ac-72e9-add9-425a49391069',
                'name' => 'UsStatesModule.update',
                'guard_name' => 'web',
                'created_at' => '2025-09-03 07:10:45',
                'updated_at' => '2025-09-03 07:10:45',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            43 => 
            array (
                'id' => '01990e69-e8c9-7085-b36f-85e2a21928b6',
                'name' => 'UsStatesModule.destroy',
                'guard_name' => 'web',
                'created_at' => '2025-09-03 07:10:45',
                'updated_at' => '2025-09-03 07:10:45',
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            44 => 
            array (
                'id' => '03d6bd9f-f3bb-4bb0-858b-2ecf7699e870',
                'name' => 'ProvinceModule.read',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            45 => 
            array (
                'id' => '048b1a55-121e-4a9c-80bd-9e556cf48655',
                'name' => 'RegioniModule.read',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            46 => 
            array (
                'id' => '09d31f9b-6d2c-4d2d-8ef3-8641ba47060a',
                'name' => 'UserWebsitesModule.create',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            47 => 
            array (
                'id' => '16fcdddf-c8e1-4989-a128-21925f42f145',
                'name' => 'WebsitesModule.update',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            48 => 
            array (
                'id' => '179541e1-412b-42f8-872a-ce8232f2799d',
                'name' => 'MediaLibraryModule.update',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            49 => 
            array (
                'id' => '1995507b-e037-46d9-b778-d07e36514035',
                'name' => 'UserWebsitesModule.destroy',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            50 => 
            array (
                'id' => '19bdc447-a40c-4066-8a1c-cd4dc4c358ef',
                'name' => 'ResourcesLangModule.destroy',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            51 => 
            array (
                'id' => '1ef350b2-315e-4572-b810-1fd32343da79',
                'name' => 'MediaLibraryModule.read',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            52 => 
            array (
                'id' => '215b3d07-4df2-4823-a73e-713f40d0c054',
                'name' => 'RolesModule.destroy',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            53 => 
            array (
                'id' => '221a3a2a-d998-4439-a864-cd818ae8bb9b',
                'name' => 'WebsitesModule.read',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            54 => 
            array (
                'id' => '277a6e60-c302-4ed0-a339-a46b06046d0c',
                'name' => 'UserWebsitesModule.read',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            55 => 
            array (
                'id' => '2974a63b-85e3-4c8a-a70b-1f96b673a0c8',
                'name' => 'RegioniModule.update',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            56 => 
            array (
                'id' => '30de89a7-fa35-443e-b890-88d3bac79a6c',
                'name' => 'ThemesModule.create',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            57 => 
            array (
                'id' => '356a139a-b688-4821-91b4-31fecd594ef3',
                'name' => 'AddressesModule.create',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            58 => 
            array (
                'id' => '360560fb-f4ff-4df5-a16d-a1e7043e1c9a',
                'name' => 'DashboardModule.read',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            59 => 
            array (
                'id' => '381bb070-800f-4a82-9ab4-8404ad06c213',
                'name' => 'AddressesModule.destroy',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            60 => 
            array (
                'id' => '3fd83448-c8cc-409d-80da-1c7d974e9a23',
                'name' => 'UsersModule.destroy',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            61 => 
            array (
                'id' => '414ee9b9-b02a-4d73-adc3-486def09b1e3',
                'name' => 'LanguagesModule.destroy',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            62 => 
            array (
                'id' => '43acaa70-4867-40dc-a73b-d838eb49dd31',
                'name' => 'RegioniModule.create',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            63 => 
            array (
                'id' => '4625404a-85ef-4462-8c85-a0cca17c1808',
                'name' => 'UsersModule.update',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            64 => 
            array (
                'id' => '4ae62e07-ea1e-469c-b7de-67034530e226',
                'name' => 'DashboardModule.update',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            65 => 
            array (
                'id' => '51d3873d-d7c3-4ba5-8bcc-bafad25b18d6',
                'name' => 'WebsitesModule.create',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            66 => 
            array (
                'id' => '5e05c2e2-cb66-4e1b-884c-0f198a4dfdbb',
                'name' => 'ComuniModule.destroy',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            67 => 
            array (
                'id' => '6186b3b3-002f-47a1-9ca1-60860568b86c',
                'name' => 'LanguagesModule.create',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            68 => 
            array (
                'id' => '66803977-1413-49cb-8659-65b6b63c02ec',
                'name' => 'CountriesModule.create',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            69 => 
            array (
                'id' => '688aa98d-f58f-4a9a-a33e-c01380ab2d15',
                'name' => 'LanguagesModule.read',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            70 => 
            array (
                'id' => '6fb6dc15-959c-4aab-addb-e2eb5bd6718c',
                'name' => 'AddressesModule.update',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            71 => 
            array (
                'id' => '78571e2d-04c4-4785-921e-c62e3b9aa77a',
                'name' => 'RolesModule.create',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            72 => 
            array (
                'id' => '7a74565a-ac7b-4360-b927-628080490b9a',
                'name' => 'ProvinceModule.update',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            73 => 
            array (
                'id' => '86eac3e7-5e7e-464a-bff3-ea65833b94d6',
                'name' => 'CountriesModule.update',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            74 => 
            array (
                'id' => '8ba5abbc-85d4-43af-aaa9-48039a82d6fb',
                'name' => 'UsersModule.read',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            75 => 
            array (
                'id' => '8c968118-242c-4dbd-9b63-5475ea87b38b',
                'name' => 'CountriesModule.destroy',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            76 => 
            array (
                'id' => '8d0b22f3-3aaa-4bde-8452-7847164df3a2',
                'name' => 'RolesModule.read',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            77 => 
            array (
                'id' => '91277f0a-66d6-48ef-a6bb-11e9b92682ed',
                'name' => 'ComuniModule.read',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            78 => 
            array (
                'id' => '9596e016-ecd1-46bd-9146-1ccef06b4fa8',
                'name' => 'UsersModule.create',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            79 => 
            array (
                'id' => '9a312c61-009d-4841-8bf5-b2fcd8a7685c',
                'name' => 'ProvinceModule.destroy',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            80 => 
            array (
                'id' => 'a3e1d26a-70d1-4caa-b1d2-3b9d0cea292f',
                'name' => 'WebsitesModule.destroy',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            81 => 
            array (
                'id' => 'a666b251-480f-4c8c-a5d7-e2d0f726899f',
                'name' => 'RegioniModule.destroy',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            82 => 
            array (
                'id' => 'adfc9e54-6d6b-48cd-ba21-659807409c87',
                'name' => 'DashboardModule.create',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            83 => 
            array (
                'id' => 'af4f34b3-db88-42d7-814e-a8ca37129c16',
                'name' => 'ProvinceModule.create',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            84 => 
            array (
                'id' => 'b3b4cf5d-3ef9-4d01-8d3c-d33f95cb9a68',
                'name' => 'ThemesModule.update',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            85 => 
            array (
                'id' => 'b6d04298-e5b2-4ede-af01-20a55010fe73',
                'name' => 'UserWebsitesModule.update',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            86 => 
            array (
                'id' => 'b7db3400-ede5-477b-9481-b61ab26cdc27',
                'name' => 'ThemesModule.read',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            87 => 
            array (
                'id' => 'bb9b25ed-694f-48c3-bfe8-13f1793f615f',
                'name' => 'AddressesModule.read',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            88 => 
            array (
                'id' => 'c3e26ff7-73b2-4458-8692-b6b45e63c8d7',
                'name' => 'RolesModule.update',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            89 => 
            array (
                'id' => 'c959cf51-b129-4d0c-9e12-e4424018a96c',
                'name' => 'ThemesModule.destroy',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            90 => 
            array (
                'id' => 'cf6242fc-0582-438e-9c7c-1b9766b69668',
                'name' => 'ResourcesLangModule.create',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            91 => 
            array (
                'id' => 'd532c02f-090c-40d6-8f8b-3f32ad5a5f92',
                'name' => 'ResourcesLangModule.read',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            92 => 
            array (
                'id' => 'dab384dd-18f2-4a77-adc1-bcf441346b1f',
                'name' => 'MediaLibraryModule.create',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            93 => 
            array (
                'id' => 'dc063e09-d264-4857-9dcd-40fcb8541ad4',
                'name' => 'ComuniModule.create',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            94 => 
            array (
                'id' => 'e11beb58-97cb-49b1-b5fa-56bd9d617bcc',
                'name' => 'LanguagesModule.update',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            95 => 
            array (
                'id' => 'e3663fa0-2491-41b8-a2f9-ffad325040d0',
                'name' => 'CountriesModule.read',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            96 => 
            array (
                'id' => 'ee396131-4bfd-49af-a8d4-480d0aa75ebd',
                'name' => 'DashboardModule.destroy',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            97 => 
            array (
                'id' => 'f784d293-a162-4786-a22a-54cafce9b836',
                'name' => 'ComuniModule.update',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            98 => 
            array (
                'id' => 'fe850a2a-c1c5-4628-811c-963c7e569baf',
                'name' => 'MediaLibraryModule.destroy',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            99 => 
            array (
                'id' => 'ff47d333-6401-43ea-992f-a54a03544193',
                'name' => 'ResourcesLangModule.update',
                'guard_name' => 'web',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
        ));
        
        
    }
}