<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ShopsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('shops')->delete();
        
        \DB::table('shops')->insert(array (
            0 => 
            array (
                'id' => '036963c3-23de-4bdd-b584-5b4b2fc80183',
                'progId' => 1002,
                'published' => 1,
                'sequence' => 30,
                'draft' => 0,
                'title' => 'ARCAPLANET',
                'location' => 'AREA ESTERNA',
                'text' => '<p>Arcaplanet è la prima catena dedicata al pet in Italia. Nata nel 1995, è oggi leader nel settore, con più di 390 negozi distribuiti su 17 regioni. I punti vendita hanno più di 10.000 referenze e offrono una vasta scelta di prodotti; cibo, accessori e giochi, per soddisfare tutte le esigenze dei pet. Inoltre, la grande varietà di offerte e attività promozionali in continuo aggiornamento, garantiscono ai clienti risparmio e convenienza, nel massimo della qualità</p>',
                'phone' => '+3903321695608',
                'mobile' => NULL,
                'whatsapp' => NULL,
                'email' => NULL,
                'url' => NULL,
                'social_facebook' => NULL,
                'social_instagram' => NULL,
                'social_linkedin' => NULL,
                'social_twitter' => NULL,
                'social_youtube' => NULL,
                'social_tripadvisor' => NULL,
                'social_snapchat' => NULL,
                'social_tumblr' => NULL,
                'social_pinterest' => NULL,
                'social_disqus' => NULL,
                'social_dailymotion' => NULL,
                'created_at' => '2025-09-15 10:52:22',
                'updated_at' => '2025-09-15 10:52:58',
                'deleted_at' => NULL,
                'created_by' => '6376a913-517a-4437-b06c-ad5764cf6710',
                'updated_by' => '6376a913-517a-4437-b06c-ad5764cf6710',
                'deleted_by' => NULL,
            ),
            1 => 
            array (
                'id' => '29a44ac7-d160-46a6-a8df-5dd83c8b4bc0',
                'progId' => 1001,
                'published' => 1,
                'sequence' => 20,
                'draft' => 0,
                'title' => 'ALCOTT',
                'location' => '4° PIANO0332 776143',
                'text' => NULL,
                'phone' => '+390332776143',
                'mobile' => NULL,
                'whatsapp' => NULL,
                'email' => NULL,
                'url' => NULL,
                'social_facebook' => NULL,
                'social_instagram' => NULL,
                'social_linkedin' => NULL,
                'social_twitter' => NULL,
                'social_youtube' => NULL,
                'social_tripadvisor' => NULL,
                'social_snapchat' => NULL,
                'social_tumblr' => NULL,
                'social_pinterest' => NULL,
                'social_disqus' => NULL,
                'social_dailymotion' => NULL,
                'created_at' => '2025-09-15 10:44:52',
                'updated_at' => '2025-09-15 10:45:27',
                'deleted_at' => NULL,
                'created_by' => '6376a913-517a-4437-b06c-ad5764cf6710',
                'updated_by' => '6376a913-517a-4437-b06c-ad5764cf6710',
                'deleted_by' => NULL,
            ),
            2 => 
            array (
                'id' => '3629c8ae-3a8c-46da-8571-492dfe7c6cfd',
                'progId' => 1006,
                'published' => 1,
                'sequence' => 60,
                'draft' => 0,
                'title' => 'CARPISA',
                'location' => '4° PIANO',
                'text' => '<p>Lasciatevi conquistare dal mondo Carpisa: borse, piccola pelletteria, valigeria e accessori costantemente al passo con le nuove tendenze per offrirvi collezioni uniche e sempre ricche di proposte. Ogni prodotto è frutto di un ricercato design made in Italy che riesce a coniugare l’esigenza di qualità con il desiderio di stile e praticità: ecco perché gli accessori Carpisa sono prodotti glamour perfetti per ogni look, con un prezzo che saprà conquistarvi tanto quanto il loro stile.<br>Carpisa, con oltre 600 punti vendita in Italia e nel mondo, è il punto di riferimento perfetto per chi ama essere trendy nella vita di tutti i giorni!<br>Lo staff di Carpisa vi aspetta!</p>',
                'phone' => '+3903321560593',
                'mobile' => NULL,
                'whatsapp' => NULL,
                'email' => NULL,
                'url' => 'https://www.carpisa.it',
                'social_facebook' => NULL,
                'social_instagram' => NULL,
                'social_linkedin' => NULL,
                'social_twitter' => NULL,
                'social_youtube' => NULL,
                'social_tripadvisor' => NULL,
                'social_snapchat' => NULL,
                'social_tumblr' => NULL,
                'social_pinterest' => NULL,
                'social_disqus' => NULL,
                'social_dailymotion' => NULL,
                'created_at' => '2025-09-15 11:01:06',
                'updated_at' => '2025-09-15 11:01:55',
                'deleted_at' => NULL,
                'created_by' => '6376a913-517a-4437-b06c-ad5764cf6710',
                'updated_by' => '6376a913-517a-4437-b06c-ad5764cf6710',
                'deleted_by' => NULL,
            ),
            3 => 
            array (
                'id' => '71c75e2f-8f46-4e20-b6f5-a3d4a72ad472',
                'progId' => 1004,
                'published' => 1,
                'sequence' => NULL,
                'draft' => 1,
                'title' => NULL,
                'location' => NULL,
                'text' => NULL,
                'phone' => NULL,
                'mobile' => NULL,
                'whatsapp' => NULL,
                'email' => NULL,
                'url' => NULL,
                'social_facebook' => NULL,
                'social_instagram' => NULL,
                'social_linkedin' => NULL,
                'social_twitter' => NULL,
                'social_youtube' => NULL,
                'social_tripadvisor' => NULL,
                'social_snapchat' => NULL,
                'social_tumblr' => NULL,
                'social_pinterest' => NULL,
                'social_disqus' => NULL,
                'social_dailymotion' => NULL,
                'created_at' => '2025-09-15 11:00:29',
                'updated_at' => '2025-09-15 11:00:29',
                'deleted_at' => NULL,
                'created_by' => '6376a913-517a-4437-b06c-ad5764cf6710',
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            4 => 
            array (
                'id' => '7fd3edda-28c6-405c-b8b9-8b5ad4c31fbb',
                'progId' => 1003,
                'published' => 1,
                'sequence' => 40,
                'draft' => 0,
                'title' => 'BOTTEGA & NATURA',
                'location' => '3° PIANO',
                'text' => NULL,
                'phone' => '+390332746956',
                'mobile' => NULL,
                'whatsapp' => NULL,
                'email' => NULL,
                'url' => NULL,
                'social_facebook' => NULL,
                'social_instagram' => NULL,
                'social_linkedin' => NULL,
                'social_twitter' => NULL,
                'social_youtube' => NULL,
                'social_tripadvisor' => NULL,
                'social_snapchat' => NULL,
                'social_tumblr' => NULL,
                'social_pinterest' => NULL,
                'social_disqus' => NULL,
                'social_dailymotion' => NULL,
                'created_at' => '2025-09-15 10:59:45',
                'updated_at' => '2025-09-15 11:00:08',
                'deleted_at' => NULL,
                'created_by' => '6376a913-517a-4437-b06c-ad5764cf6710',
                'updated_by' => '6376a913-517a-4437-b06c-ad5764cf6710',
                'deleted_by' => NULL,
            ),
            5 => 
            array (
                'id' => '7fe33658-d8db-4f92-a8d4-742cadc3ce3a',
                'progId' => 1005,
                'published' => 1,
                'sequence' => 50,
                'draft' => 0,
                'title' => 'BLUVACANZE',
                'location' => '3° PIANO',
                'text' => '<p><br></p>',
                'phone' => '+390332730422',
                'mobile' => NULL,
                'whatsapp' => NULL,
                'email' => NULL,
                'url' => NULL,
                'social_facebook' => NULL,
                'social_instagram' => NULL,
                'social_linkedin' => NULL,
                'social_twitter' => NULL,
                'social_youtube' => NULL,
                'social_tripadvisor' => NULL,
                'social_snapchat' => NULL,
                'social_tumblr' => NULL,
                'social_pinterest' => NULL,
                'social_disqus' => NULL,
                'social_dailymotion' => NULL,
                'created_at' => '2025-09-15 11:00:42',
                'updated_at' => '2025-09-15 11:01:01',
                'deleted_at' => NULL,
                'created_by' => '6376a913-517a-4437-b06c-ad5764cf6710',
                'updated_by' => '6376a913-517a-4437-b06c-ad5764cf6710',
                'deleted_by' => NULL,
            ),
            6 => 
            array (
                'id' => 'fc15fa73-182a-44f0-a8ea-03a7603ddf81',
                'progId' => 1000,
                'published' => 1,
                'sequence' => 10,
                'draft' => 0,
                'title' => 'MACHAPOKÈ',
                'location' => '5° PIANO',
                'text' => '<p><br></p>',
                'phone' => NULL,
                'mobile' => NULL,
                'whatsapp' => NULL,
                'email' => NULL,
                'url' => NULL,
                'social_facebook' => NULL,
                'social_instagram' => NULL,
                'social_linkedin' => NULL,
                'social_twitter' => NULL,
                'social_youtube' => NULL,
                'social_tripadvisor' => NULL,
                'social_snapchat' => NULL,
                'social_tumblr' => NULL,
                'social_pinterest' => NULL,
                'social_disqus' => NULL,
                'social_dailymotion' => NULL,
                'created_at' => '2025-09-01 08:14:43',
                'updated_at' => '2025-09-15 10:46:26',
                'deleted_at' => NULL,
                'created_by' => 'c2777a10-999e-42f2-bce8-4100579834f3',
                'updated_by' => '6376a913-517a-4437-b06c-ad5764cf6710',
                'deleted_by' => NULL,
            ),
        ));
        
        
    }
}